### ISSUE TITLE
Not compatible with updated Homebridge and iOS 10

### ISSUE THREAD

**Issue by felixekman** [jchnlemon/homebridge-telldus#13]
Does not respond properly with correct unit status or control ability.

**Comment by steam0** [comment]
Could you elaborate?

**Comment by gustafnilklint** [comment]
In the "Home"-app in iOS 10 it is not possible to read status of the Telldus switches. Further not possible to change state on/off.
Although it still works with 3:e party app like insteon and with Siri. Anyone else experiencing this issue?
I tried to re-create the home in HomeKit and also removing the settings in homebridge. The problem remains.
According to the main project for homebridge this is not an issue.. this is why I'm suspecting that it is the telldus plugin that has an issue..

**Comment by felixekman** [comment]
Thank you for clarifying. I've been bug hunting like crazy and tried rebuilding like you, but to no avail. Truly seems to be the plugin:-/

**Comment by jchnlemon** [comment]
Hi, unfortunately I have no time to look into this. It might be so that the values sent to homebridge-telldus have changed and therefore cannot be processed correctly?

**Comment by tvillingett** [comment]
It works for me on iOS 10 GM. Can you see anything in the log-output?

**Comment by steam0** [comment]
@tvillingett What "model type" is your switches recognized as?

Mine are recognized as [selflearning-switch](http://imgur.com/i9XI8XC), and I think that might be wrong.
