### ISSUE TITLE
Is the development abandoned?

### ISSUE THREAD

**Issue by MichaelMMX** [jchnlemon/homebridge-telldus#15]
With iOS 10 less than a week away, and pulrequests that are months old, you start to wonder. Is there any other plugin for Telldus Live! where development is still ongoing, and that works with iOS 10?

**Comment by jchnlemon** [comment]
No it is not abandoned. I haven't had time to work on it for the past couple of months. This means that there is no working version for iOS 10 from my side. I will have time to update it end of September/beginning of October, but for now you will have to rely on yourself or someone else to make a pull request with a working version for iOS 10.
