### ISSUE TITLE
Telldus Live "No Response" on iOS 10

### ISSUE THREAD

**Issue by olavhaugen** [jchnlemon/homebridge-telldus#16]
Hi,

I've just installed homebridge and homebridge-telldus from my Mac using the following commands:

`npm install -g homebridge` 
`npm install -g homebridge-telldus` 

Then, I went to ~/.homebridge/ and edited the config.json to following (keys are omitted):

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "My home",
    "platforms": [
        {
            "platform" : "Telldus",
            "name" : "Telldus Live!",
            "public_key" : "secret",
            "private_key" : "secret",
            "token" : "secret",
            "token_secret" : "secret"
        }
    ],
    "accessories": [
    ]
}
```

I run the `homebridge` command from the Terminal, and everything looks well. All my lights and switches are discovered.

I'm running the GM of iOS 10 on my iPhone 6. I load up HomeKit and is able to find homebridge. After adding homebridge I get a grid displaying all my lights, but they all have the text "No Response" under them. When I try to interact with any of them, nothing happens.

Any idea why it is not working?

**Comment by steam0** [comment]
I have the same problem. Please highlight me if you solve this problem.

To add some information to this problem: In the home-app I can see that my power outlets are registered as a `selflearning-switch` and I have no idea how to change it from that to a normal power outlet

**Comment by steam0** [comment]
@olavhaugen Have you tried the updated version of homebridge-telldus? I will close this issue if you do not respond

**Comment by olavhaugen** [comment]
Yes, I just tried it, and can verify that it now works 👍
