### ISSUE TITLE
UUID conflict using zwave device with multiple functions

### ISSUE THREAD

**Issue by mknuts** [jchnlemon/homebridge-telldus#20]
Get the following error when I start homebridge:

[2016-10-30 11:41:34] [Tells Live!] Initializing platform accessory 'Växthus LED'...
[2016-10-30 11:41:34] [Tells Live!] Initializing platform accessory 'Energi Poolpumpen'...
[2016-10-30 11:41:34] [Tells Live!] Cannot add a bridged Accessory with the same UUID as another bridged Accessory: d4fe138d-3942-4ed0-999c-6efe6f178c16
Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: d4fe138d-3942-4ed0-999c-6efe6f178c16

I'm pretty sure that the reason is that I have a number of Fibaro zwave wallpluggs that has a built in energy monitor. This means that Telldus has one device (switch) and one sensor with exactly the same name. If you use the telldus live GUI to change the name on these sensors OR devices then the name is always changed on both the device and sensor at the same time. Previously it was possible to use the telldus API and change the name of the device without changeing the sensor name and I used that as a workaround, but now Telldus has changed the API so when I use device/setName OR sensor/setName it changes both.... according to Telldus support this was a bug that they have corrected...

Any idea how this can be solved?
My workaround for now is to hide these sensors in telldus-live GUI

**Comment by mifi** [comment]
Hi
I added a possibility in my fork to set custom name on devices. This is done using the unknown_devices config property in .homebridge/config.json. It will now also allow for selectively altering individual device attributes (like only name.)
See https://github.com/mifi/homebridge-telldus/blob/master/config.json for example config.

To install my fork:
npm install -g git+https://github.com/mifi/homebridge-telldus.git

**Comment by mknuts** [comment]
Hi,

Thanks! 
Your fork solved my problem! Great work!

**Comment by mifi** [comment]
#21
