### ISSUE TITLE
Uppdate the package version

### ISSUE THREAD

**Issue by nklint** [jchnlemon/homebridge-telldus#29]
Hi! It's refreshing with the high activity in this repo. Things are moving forwards, but the version is standing still..
If the version is not changed it not possible to update with npm. I have to uninstall and re-install instead. Or am I doing it wrong?
It seems more convenient if I can npm update.

**Comment by mifi** [comment]
Hi. I absolutely agree.
The owner of this project is very busy and has not given me npm publish access yet. I will ask him once more, and if not then I could publish my own fork under a separate npm name.

**Comment by mifi** [comment]
New version is released. 0.0.5.
