### ISSUE TITLE
Temperature sensor is not supported?

### ISSUE THREAD

**Issue by tvillingett** [jchnlemon/homebridge-telldus#3]
Hi, I cannot see that temperature sensors are shown. Is there any support for them now?

**Comment by jchnlemon** [comment]
Hi, no unfortunately it is not supported. The simple answer to why it isn't supported is because i have no sensors connected to my account. However it shouldn't be hard to implement, you could try it yourself and make a pull request or wait and I'll try to do it during the holidays :)!

**Comment by tvillingett** [comment]
I guess it is not so hard too... I try hard to get into the github, npm, node.js, homekit spec, mqtt, raspberry pi, and so on. But I will get around it...

I have rest of my home automation in node-red, so I would prefer i someone could do something for  homekit that could be used as blocks inside there.

**Comment by steam0** [comment]
Support for temperature sensors are now implemented.
