### ISSUE TITLE
Error - split of null

### ISSUE THREAD

**Issue by rirofal** [jchnlemon/homebridge-telldus#30]
Got a strange error...

![image](https://cloud.githubusercontent.com/assets/3245006/20056925/ec148c66-a4e8-11e6-9f79-24e7fe7e50d7.png)

**Comment by mifi** [comment]
Which version are you running?

**Comment by rirofal** [comment]
Running on a Synology inside Docker... so npm is running latest... I hope. :)

This is the docker config:
`{  "scripts": {
    "install": "npm install -g homebridge-synology homebridge-sonos homebridge-telldus --unsafe-perm"
  }
}
`

**Comment by rirofal** [comment]
Found a device that probably is causing some issues (model = null) ... 

Result from the API:

`{"id":"9999462","name":"Ljusslang","state":"0","statevalue":"0","methods":"0","type":"device","client":"215603","protocol":null,"model":null,"online":"1","editable":1,"parameter":[]}`

**Comment by mifi** [comment]
You can temporarily try:
npm install -g git+https://github.com/jchnlemon/homebridge-telldus.git

Some fixes have not yet been published on npm. I hope to get npm publish access from owner soon. See also #29

**Comment by rirofal** [comment]
Looks like it works a lot better...  :)

(got a couple of other errors... will look in to them later on)

My docker config right now:
`{  "scripts": {
    "install": "npm install -g homebridge-synology homebridge-sonos git+https://github.com/jchnlemon/homebridge-telldus.git --unsafe-perm"
  }
}
`

**Comment by mifi** [comment]
note however that you should go back to npm install homebridge-telldus when a new version is published in npm, because the git+https is master which can be unstable

**Comment by mifi** [comment]
New version has now been deployed on npm, 0.0.5. You should use that now. Closing this
