### ISSUE TITLE
Configuration of Z-wave switches with built-in power measuring sensors

### ISSUE THREAD

**Issue by Bjsulla** [jchnlemon/homebridge-telldus#32]
Trying to add a Qubino Flush 2 Relay Z-wave device generates an error. The error gets generated because the device also contains a sensor that measure power consumption. The name of the switch and and the name of the sensor is the same and can not be changed independently of each other in Telldus Live.

If I deselect "Show in list" in Telldus Live the error does not occur but as soon as a sensor is selected I get the same error about UUID is the same.

Error message
`Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: be10f4a9-6154-432c-b5fb-042598526eda
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222:13)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:364:24)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at TelldusLive.loginAsync.then.then.accessories (/usr/lib/node_modules/homebridge-telldus/index.js:116:6)
    at tryCatcher (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/homebridge-telldus/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
`

**Comment by mifi** [comment]
See #20

**Comment by Bjsulla** [comment]
Deselecting the sensors in Telldus Live allows me to see the id of the sensors and configure the with a different name in config.json. After this homebridge starts up without complaining about the same UUID. I have the power measuring sensors configured as "temperaturehumidity" in the config.json.

When starting up the Home app on the iPhone Homebridge crashes with another error. I tried to configure the sensors both as "temperaturehumidity" and "temperature" with the same result.

`TypeError: Cannot read property '0' of undefined
    at cx.getValueFromDev.dev [as getValueFromDev] (/usr/lib/node_modules/homebridge-telldus/index.js:286:53)
    at TelldusLive.getSensorInfo (/usr/lib/node_modules/homebridge-telldus/index.js:291:70)
    at /usr/lib/node_modules/homebridge-telldus/node_modules/telldus-live/telldus-live.js:192:5
    at /usr/lib/node_modules/homebridge-telldus/node_modules/telldus-live/telldus-live.js:233:7
    at passBackControl (/usr/lib/node_modules/homebridge-telldus/node_modules/oauth/lib/oauth.js:390:11)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-telldus/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by mifi** [comment]
A power sensor is not the same as a temperature humidity sensor, no? Please run with debug mode and share output. See other issues how this is done. Then maybe a power sensor can be implemented. However i dont know if Apple Homekit supports power senSors.

**Comment by Bjsulla** [comment]
Thank you

I will try to run the debug but in the meantime is there a way to disable the sensors in the config.json?

**Comment by mifi** [comment]
No, but you can try to set name to empty in telldus if that's possible. then they should be ignored

**Comment by Bjsulla** [comment]
Setting names as empty does not work unfortunately. I included the log files, please let me know if they are sufficient.

Homekit seem to support power sensors according to the Elgato Eve Energy which is capable of power metering with Homekit (https://www.amazon.com/Elgato-Energy-HomeKit-Technology-Bluetooth/dp/B01BFXX3D6)

[homebridge.err.txt](https://github.com/jchnlemon/homebridge-telldus/files/627965/homebridge.err.txt)
[homebridge.log.txt](https://github.com/jchnlemon/homebridge-telldus/files/627966/homebridge.log.txt)

**Comment by mifi** [comment]
Thanks. Setting names as empty does not work as in: it is not possible to do in telldus web admin?

**Comment by mifi** [comment]
Looking at your logs, I can't see any sensors. (getSensors returns empty list). And no device seems to be generating any interesting values (e.g power measurements)

```
{ id: '1415831',
  name: 'Sensor-Q1',
  state: '2',
  statevalue: null,
  methods: '3',
  type: 'device',
  client: '221117',
  protocol: 'zwave',
  model: 'n/a',
  online: '1',
  editable: 1,
  parameter: [],
  status: 'off' }
```

**Comment by Bjsulla** [comment]
It works in Telldus web but Homekit loads the devices anyway. Beside the sensor can't have different name then the switch which makes it (ehmm) interesting to find the right switch in Telldus web.

The Sensors are named as Sensor-* as custom names in the config.json. Since the switches are brand new there aren't any values yet. I'll update tomorrow when they are connected to some load and with actual values.

Thank you for your help.

**Comment by mifi** [comment]
I've added a flag for disabling a device. See sample config.json:
https://github.com/mifi/homebridge-telldus/blob/master/config.json

You have to use my fork for now:
npm install -g git+https://github.com/mifi/homebridge-telldus.git

**Comment by mknuts** [comment]
I also have some energy sensors, and here is the output from one of them:

{"id":"7519745","clientName":"ZNet","name":"Uterum","lastUpdated":1480748683,"ignored":0,"editable":1,"data":[{"name":"watt","value":"75.04","scale":"0","lastUpdated":1480748683.001,"max":"7383","maxTime":1475384365.5674},{"name":"watt","value":"0.0","scale":"2","lastUpdated":1480748683.001,"max":"1278.2","maxTime":1476039436.1557}],"protocol":"zwave","sensorId":"175","timezoneoffset":3600,"battery":"254","keepHistory":"1"}

Interpreted by Telldus app it says that the current consumption is 0.0 W and the total consumption is 75.04 kWh.

**Comment by krfr** [comment]
I'm using Telldus Live with Tellstick ZNet Lite (and mostly zwave-devices) and I have the same problem with the sensors. The only solution that works for me has been to use jchnlemon's sollution for unknown-model-support as described in this thread: https://github.com/jchnlemon/homebridge-telldus/issues/1#issuecomment-158244847

**Comment by mifi** [comment]
@mknuts @Bjsulla I think Apple HomeKit doesn't support energy readers yet.
See https://github.com/KhaosT/HAP-NodeJS/issues/174

@krfr master branch also works with unknown devices now.

**Comment by krfr** [comment]
Hmm.. 
I tried using the master branch and then nothing works at all. "The device is not supported" it says in HomeKit.
I also get the error message "Can not add a bridged Accessory With The Same UUID as another bridged Accessory" with the master branch unless I turn off the sensors in Telldus. But I still want to see the energy sensors in Telldus own app.

**Comment by mifi** [comment]
_model_ changed from unknown-* to selflearning-*, see https://github.com/jchnlemon/homebridge-telldus/issues/1#issuecomment-253987824

As for "Can not add a bridged Accessory With The Same UUID as another bridged Accessory":
Can you try to install my fork instead?
npm install -g git+https://github.com/mifi/homebridge-telldus.git
And then i in config.json, use the disabled field for those ID's that fail with this error.
See example of using disabled here:
https://github.com/mifi/homebridge-telldus/blob/master/config.json

**Comment by mifi** [comment]
Have now release 0.0.6 in npm with suport for "disabled". See also main readme file

**Comment by Bjsulla** [comment]
Works great with disabling devices after the update. But the zwave switches no longer work. Homekit shows that the switch turn off/on but there is no command sent to Telldus.

Following is in the error log:
`Sat, 03 Dec 2016 13:51:38 GMT EventedHTTPServer [::ffff:10.121.10.167] HTTP request: /characteristics
Sat, 03 Dec 2016 13:51:38 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics
Sat, 03 Dec 2016 13:51:38 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":49,"iid":9,"value":0}]
Sat, 03 Dec 2016 13:51:38 GMT Accessory [Homebridge] Setting Characteristic "On" to value 0
Sat, 03 Dec 2016 13:51:38 GMT EventedHTTPServer [::ffff:10.121.10.167] Muting event '49.9' notification for this connection since it originated here.
Sat, 03 Dec 2016 13:51:38 GMT EventedHTTPServer [::ffff:10.121.10.156] Sending HTTP event '49.9' with data: {"characteristics":[{"aid":49,"iid":9,"value":0}]}
Sat, 03 Dec 2016 13:51:38 GMT EventedHTTPServer [::ffff:10.121.10.167] HTTP Response is finished
Sat, 03 Dec 2016 13:51:47 GMT EventedHTTPServer [::ffff:10.121.10.167] HTTP request: /characteristics
Sat, 03 Dec 2016 13:51:47 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics
Sat, 03 Dec 2016 13:51:47 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":49,"iid":9,"value":1}]
Sat, 03 Dec 2016 13:51:47 GMT Accessory [Homebridge] Setting Characteristic "On" to value 1
Sat, 03 Dec 2016 13:51:48 GMT EventedHTTPServer [::ffff:10.121.10.167] Muting event '49.9' notification for this connection since it originated here.
Sat, 03 Dec 2016 13:51:48 GMT EventedHTTPServer [::ffff:10.121.10.156] Sending HTTP event '49.9' with data: {"characteristics":[{"aid":49,"iid":9,"value":1}]}
Sat, 03 Dec 2016 13:51:48 GMT EventedHTTPServer [::ffff:10.121.10.167] HTTP Response is finished
`

**Comment by mifi** [comment]
You say no longer work. When did they work? With which version?

**Comment by Bjsulla** [comment]
No longer works is a poor word of choice because this is my first try to get the zwave switches to work, meaning I haven't really got it to work at all yet :-(

**Comment by mifi** [comment]
`Pressing the switch in Home turns the switch off/on.`

So only reading status is not working?

**Comment by Bjsulla** [comment]
Only GUI in the Home app gets updated as on/off. Not the physical zwave switch, it seems like the command gets muted in the log above.

**Comment by mifi** [comment]
Its hard for me to figure out how to turn this device on/off without having an actual device to test with.
If you can find out how to turn it on/off and get status using the api explorer then maybe we can use that.

**Comment by krfr** [comment]
Struggeling to make it work with Master Branch.. no luck, however.
Did make an new fresh install also.

If I use Maser Branch noting work att all... No buttons in Home-App neither use with Siri.

if I use "npm install -g git+https://github.com/jchnlemon/homebridge-telldus.git#unknown-model-support" atleast i can manage to use Sirir, and sometimes also buttons i the Home-App.

Function to disable sensors works, so problem with UUID seems solved.

**Comment by mknuts** [comment]
Hmm... my zwave switches works, never had any problem with them since I got the version from @mifi that could specify a different name for the sensor.

**Comment by krfr** [comment]
@mknuts Do you mean Master Branch or his latest fork?

**Comment by mknuts** [comment]
No, it's, his fork but it is a couple of weeks old. I will try the never version tomorrow.

**Comment by krfr** [comment]
Weird... tried to install the Master Branch again this morning, and everything works as it should now.

**Comment by Bjsulla** [comment]
Thanks @krfr. I did also a clean fresh install today and everything works perfectly.

**Comment by mknuts** [comment]
Updated to latest master branch, works as expected, but I saw that the works for you guys as well.

**Comment by mifi** [comment]
So all is working and we can close this?

**Comment by mknuts** [comment]
If Apple HomeKit does'nt support power measuring and the switches works... then my answer is yes!

**Comment by Bjsulla** [comment]
Yes. Great work!

**Comment by mifi** [comment]
Great. it seems Apple official homekit doesnt support it. I think some unofficial apps do, however.
