### ISSUE TITLE
Support for Fibrao Wall-plug?

### ISSUE THREAD

**Issue by xtiancma** [jchnlemon/homebridge-telldus#36]
I am (using telldus live) running a telldus net and a telldus z-wave lite with both 433 and z-wave sensors and switches. Fired up homebridge on an very old mac mini, and after some work I got most stuff up and working via the home kit app. 
I see there is an issue with Fibrao z-wave sensors. Like the multiisensor (the eye), since it register in telldus live both as a device and sensor ie with the same name. this will give the "dual uuid" error. I fixed this by naming it by means of the parameter "user defined name" (config.json). This will end up giving the sensor 2 UUIDs, but I set the second one as "disabled". works fine.
But the Fibra Wall-plug, which is a on/off switch and measures power use - I cant get to work. adding it as a "wall-plug" fails, adding it as a "selflearning-switch" works (and using user defined name and disable the second uuid"), but it does not perform any action (ie does not turn on nor off). Watt measure data is not working either.
Is it anyway to get is working?

**Comment by mifi** [comment]
selflearning-switch uses the api onOffDevice.
Is that working?
http://api.telldus.com/explore/device/turnOn

If not, yhou need to figure out how to turn the device on/off with the telldus api.

**Comment by xtiancma** [comment]
hmm.. that actually worked fine via the api gui.. then I need to figure out why it does nothing when I try to turn it on via the homekit app

**Comment by mifi** [comment]
DEBUG=homebridge-telldus homebridge might provide some clues

**Comment by xtiancma** [comment]
Thanks, works now. Since I get 2 id numbers from these fibrao z-wave sensors - I need to set 1 of each to disable = true. Seems I must have disabled the "wrong" id number. Now it works :-)

**Comment by mifi** [comment]
Ook. closing this
