### ISSUE TITLE
The ON/OFF value don't change from telldus

### ISSUE THREAD

**Issue by tvillingett** [jchnlemon/homebridge-telldus#4]
Even though I have change my fork for the reading from Telldus to:
```javascript
            switch (characteristic) {
                case Characteristic.Formats.BOOL:
                    newState = that.device.state == 1 ? true : false; // Telldus 1=ON, 2=OFF
                    break;
```
so it sends true and false for open close, it still dont update the readback values on the iphone, only when the phone itself sets the values.

Tested on both Elgato Eve and Insteon+, and the log shows that it updates the values on refresh, but nothing changes in the app.

**Comment by jamesw4** [comment]
Did you get anywhere with this? Trying to achieve the same thing but not having much luck.

**Comment by tvillingett** [comment]
No I didn't. Have you tested any working implementation of lightbulb or switch that reports correctly to HK? I think that is the way
to go forward, I suspect that it is not reporting on the correct characteristics.  There is also some strange behaviour when dimming also, and the dimming reports back odd values in the user interface in Eve, I haven't found the pattern on that yet.

**Comment by tvillingett** [comment]
I found the error in index.js:
the callback should both return "err null" first, and then the state (line 172)
```javascript
            that.log("Updated state " + characteristic + " : " + newState);
            callback( false, newState );
```
it was actually signalling err when the lamp is on, as it was implemented:
(old code)
```javascript
            callback( newState );
```
It works for me now!

I will make a pull request.

**Comment by jchnlemon** [comment]
Hi, sorry for not responding you, I've been on vacation for some time. 

@tvillingett I saw that you created a pull request and closed it recently, do you still want to do it or is it something that isn't working atm?

**Comment by tvillingett** [comment]
I made a new pull req., not really into how to work with github - yet...
