### ISSUE TITLE
Where to find device id?

### ISSUE THREAD

**Issue by Nystro0m** [jchnlemon/homebridge-telldus#40]
Hi, im trying to modify some of my self-learning switches to normal switches. Because as they show up as light bulbs.
I understand how to edit my config.json.

However, trough Telldus live i can only find my ID for my sensors. 
Which in this case wont be added, even if i add them manually in the config.

Where can i find my ID's to the config on my 433MHz units?

Thanks all the work you have put in to this.
Im super grateful.

**Comment by krfr** [comment]
In API Explorer you can find all ID's for your Units. 
http://api.telldus.com/explore/devices/list
