### ISSUE TITLE
Telldus plugin cannot start

### ISSUE THREAD

**Issue by SWEiNSANE** [jchnlemon/homebridge-telldus#45]
I just replaced my old Raspberry Pi with a model 3 so I set up Homebridge with Trådfri plugin and Telldus plugin along with the latest Raspbian Jessie Lite, npm and node.js.

But now the Telldus plugin cannot start as Homebridge. I get this error message:

[5/6/2017, 1:37:21 PM] [Telldus Liv!e] undefined
Unhandled rejection (<{"statusCode":401,"data":"{\"error\":\...>, no stack trace

Any suggestions? I reinstalled everthing once again but no luck :-(

**Comment by mifi** [comment]
can you try to make requests manually against the telldus API? using the API explorer or CURL/Postman?

http://api.telldus.com/explore/index

**Comment by SWEiNSANE** [comment]
It worked great with API Explorer so I copied my keys once again to config.json and now the error is gone :-) It looks like the first character was missing, embarrassing newbie error...

Thanks for pointing me in the right direction!
