### ISSUE TITLE
TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by SubZane** [jchnlemon/homebridge-telldus#46]
When trying to run it after entering all the API keys I get the following unknown error

Any idea?

/usr/lib/node_modules/homebridge-telldus/node_modules/telldus-live/telldus-live.js:221
      if (!!err) return callback(err, response.statusCode);
                                              ^

TypeError: Cannot read property 'statusCode' of undefined
    at /usr/lib/node_modules/homebridge-telldus/node_modules/telldus-live/telldus-live.js:221:47
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-telldus/node_modules/oauth/lib/oauth.js:421:9)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by mifi** [comment]
Seems there is a bug in telldus-live npm module that we depend on.
https://github.com/TheThingSystem/node-telldus-live/pull/9

Maybe there is something wrong with the network or something?

**Comment by SubZane** [comment]
It turns out that there was an error in the config.json, maybe a typographic qutationmark or something, because it worked after I ran the config through a jsonlint, formatted it neatly and pasted it back again.

**Comment by SubZane** [comment]
As it turns out, my raspberry pi also had lost internet connection :P

**Comment by carlfranzon** [comment]
I got this problem when the Telldus Live! service was down, so it is most likely due to connection issues.

**Comment by SubZane** [comment]
ah yes that could be it as well. Maybe clearer error reporting could be done? if not, add a faq? :)

**Comment by mifi** [comment]
Like I said, this is a bug in https://github.com/TheThingSystem/node-telldus-live/pull/9
Seems that project is not being maintained, so we could write a replacement for it, but I don't have time for that now.

I'll add an FAQ 👍

**Comment by danielkihlgren** [comment]
Should this be closed? I'm often having problems with this since it shuts down my homebridge server. It seems to be fixed in https://github.com/arevenes/node-telldus-live Maybe that should be used instead?

**Comment by mifi** [comment]
The maintainer of https://github.com/TheThingSystem/node-telldus-live should merge the PR

**Comment by danielkihlgren** [comment]
It’s merged now
